### ISSUE TITLE
It returns nil when the address contains P.O Box

### ISSUE THREAD

**Issue by sachinprasad** [derrek/street-address#13]
Hi it is returning nil when my address is 'P. O. Box 1410 Durham, NC 27702'. And when  P. O. Box is replace with ' ' it can parse other details. 

For other address types here is a good list http://stackoverflow.com/questions/16413/parse-usable-street-address-city-state-zip-from-a-string

**Comment by derrek** [comment]
This is kind of fixed with version 2.  It parses although the stringified output might not be what you expect.
