### ISSUE TITLE
PO box not parsing properly.

### ISSUE THREAD

**Issue by sachinprasad** [derrek/street-address#14]
Here is my irb console  report: 

a = StreetAddress::US.parse("1410 Durham, NC 27702")
=> 141 0, Durham, NC 27702
irb(main):010:0> a.number
=> "141"

It should be 1410 but it is returning 141.

It is also same when I'm trying this:

irb(main):004:0> a = StreetAddress::US.parse("1600 Washington, DC, 20500")
=> 160 0, Washington, DC 20500
irb(main):005:0> a.number
=> "160"

**Comment by derrek** [comment]
I can't reproduce this.  @sachinprasad it has been a long time.  Do you still see this problem?  If so what version of the gem?

**Comment by lulalalalistia** [comment]
@derrek I have tested. This bug was fixed on master branch, but not on the latest gem (1.0.6).
Do you still plan to release a new version? Cheers~~
