### ISSUE TITLE
Addresses with grid system displays incorrectly 

### ISSUE THREAD

**Issue by zhon** [derrek/street-address#9]
Version 1.0.5

```ruby
a = StreetAddress::US.parse(
  '88 E 1160 S SUITE A, ST GEORGE, UT')
a.to_s  # => "88 E 1160 Suite A S, ST GEORGE, UT"
```

It seems like the street suffix is displayed after the unit_prefix and unit.

Love the gem, BTW.

**Comment by derrek** [comment]
Kinda fixed in version 2.  Not totally sure what you would expect for #street and #number.
